# This is a basic workflow to help you get started with Actions

name: Damage Caluculation Test

# Controls when the action will run. 
on:
  push:
    branches: [ master ]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v10.14.2
        uses: actions/setup-node@v1
        with:
          node-version: '10.14.2'
          
      - run: yarn install
      - run: yarn test
